import * as React from "react";

// Next.js
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";

// Modules
import {
  Calendar,
  Footer,
  Group,
  Header,
  LegendModal,
  SettingModal,
} from "@/components";
import dayjs from "dayjs";
import useLocalStorageState from "use-local-storage-state";

// Styles
import LoaderModal from "@/components/modals/loaderModal";
import styles from "@/styles/pages/Home.module.scss";

export default function Home() {
  const { data: session } = useSession();
  const refEl: any = React.useRef<HTMLInputElement>();
  const [year, setYear] = React.useState<string>(dayjs().format("YYYY"));
  const [month, setMonth] = React.useState<string>(dayjs().format("M"));
  const [legendVisible, setLegendVisible] = React.useState<boolean>(false);
  const [settingVisible, setSettingVisible] = React.useState<boolean>(false);
  const [loadingVisible, setLoadingVisible] = React.useState<boolean>(false);
  const [settings, setSettings] = useLocalStorageState("settings", {
    defaultValue: {
      colors: {
        completed: "#ffa500",
        first_episode: "#800080",
        upcoming_episode: "#6495ed",
        airing: "#02a9ff",
      },
      filters: {
        type: "anime",
        show_upcoming_ep: false,
        show_only_first: false,
        show_completed: true,
        show_airing: true,
      },
      cardSettings: {
        sizeMode: "auto",
        manualSize: "medium",
      },
    },
  });
  return (
    <>
      <Head>
        <title>AniCalendar - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        {!session && (
          <div className={styles.heroContainer}>
            <div className={styles.backgroundPattern}>
              <div className={styles.gridLine}></div>
              <div className={styles.gridLine}></div>
              <div className={styles.gridLine}></div>
            </div>

            <div className={styles.heroContent}>
              <h1 className={styles.heroTitle}>
                <span className={styles.titleMain}>Your Anime & Manga</span>
                <span className={styles.titleGradient}>In One Calendar</span>
              </h1>

              <p className={styles.heroDescription}>
                Connect your AniList account to automatically retrieve all your
                watching activities. View upcoming episodes, movies, ONA, and
                manga chapters organized in a beautiful calendar view with
                customizable colors and filters.
              </p>

              <div className={styles.featuresGrid}>
                <div className={styles.featureCard}>
                  <div className={styles.featureIconWrapper}>
                    <svg
                      className={styles.featureSvg}
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
                      <line x1="16" y1="2" x2="16" y2="6" />
                      <line x1="8" y1="2" x2="8" y2="6" />
                      <line x1="3" y1="10" x2="21" y2="10" />
                    </svg>
                  </div>
                  <h3 className={styles.featureTitle}>Calendar View</h3>
                  <p className={styles.featureDesc}>
                    See all your activities organized by release date
                  </p>
                </div>

                <div className={styles.featureCard}>
                  <div className={styles.featureIconWrapper}>
                    <svg
                      className={styles.featureSvg}
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
                      <polyline points="3.27 6.96 12 12.01 20.73 6.96" />
                      <line x1="12" y1="22.08" x2="12" y2="12" />
                    </svg>
                  </div>
                  <h3 className={styles.featureTitle}>API Integration</h3>
                  <p className={styles.featureDesc}>
                    Fetches your data directly from AniList API
                  </p>
                </div>

                <div className={styles.featureCard}>
                  <div className={styles.featureIconWrapper}>
                    <svg
                      className={styles.featureSvg}
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <circle cx="12" cy="12" r="3" />
                      <path d="M12 1v6m0 6v6M4.22 4.22l4.24 4.24m5.08 5.08l4.24 4.24M1 12h6m6 0h6M4.22 19.78l4.24-4.24m5.08-5.08l4.24-4.24" />
                    </svg>
                  </div>
                  <h3 className={styles.featureTitle}>Customizable</h3>
                  <p className={styles.featureDesc}>
                    Personalize colors, filters, and display options
                  </p>
                </div>
              </div>

              <div className={styles.ctaContainer}>
                <button
                  className={styles.signInButton}
                  onClick={() => signIn()}
                >
                  <svg
                    className={styles.anilistIcon}
                    viewBox="0 0 24 24"
                    fill="currentColor"
                  >
                    <path d="M6.361 2.943L0 21.056h4.942l1.077-3.133H11.4l1.052 3.133H22.9c.71 0 1.1-.392 1.1-1.101V17.53c0-.71-.39-1.101-1.1-1.101h-6.483V4.045c0-.71-.392-1.102-1.101-1.102h-2.422c-.71 0-1.101.392-1.101 1.102v1.064l-.758-2.166zm2.324 5.948l1.688 5.018H7.144z" />
                  </svg>
                  <span>Connect with AniList</span>
                  <svg
                    className={styles.arrowIcon}
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2.5"
                  >
                    <path d="M5 12h14M12 5l7 7-7 7" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        )}
        {session?.user && (
          <>
            <LegendModal
              setVisible={setLegendVisible}
              visible={legendVisible}
            />
            <SettingModal
              setVisible={setSettingVisible}
              visible={settingVisible}
            />
            <LoaderModal
              setVisible={setLoadingVisible}
              visible={loadingVisible}
            />
            <Group
              refElement={refEl}
              year={year}
              month={month}
              setMonth={setMonth}
              setYear={setYear}
              setLegendVisible={setLegendVisible}
              setSettingVisible={setSettingVisible}
              setLoadingVisible={setLoadingVisible}
            />

            <Calendar refElement={refEl} year={year} month={month} />
          </>
        )}
      </main>
      <Footer />
    </>
  );
}
