import * as React from "react";

// Next.js
import Head from "next/head";

// Modules
import { Header, Footer } from "@/components";

// Styles
import styles from "@/styles/pages/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>AniCalendar - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Unleash the <span className={styles.anilist}>Power of Nostalgia</span>
        </h1>
        <h2 className={styles["sub-title"]}>
          Dive into Your Anime and Manga Journey on a Dynamic Calendar!
        </h2>
        <button className={styles.button}>Start exploring soon!</button>
      </main>
    </>
  );
}
