import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useSession } from "next-auth/react";
import * as React from "react";
import dayjs from "dayjs";
import { CalendarButtons, Calendar, Header } from "@/components";

export default function Home() {
  const { data: session } = useSession();
  const domEl: any = React.useRef<HTMLInputElement>();
  const [year, setYear] = React.useState<string>(dayjs().format("YYYY"));
  const [month, setMonth] = React.useState<string>(dayjs().format("M"));

  return (
    <>
      <Head>
        <title>AniCalendar - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        {!session && (
          <>
            <h1>Sign in to view your calendar.</h1>
          </>
        )}
        {session?.user && (
          <>
            <CalendarButtons
              refOne={domEl}
              year={year}
              month={month}
              setMonth={setMonth}
              setYear={setYear}
            />

            <Calendar refOne={domEl} year={year} month={month} />
          </>
        )}
      </main>
    </>
  );
}
